### ISSUE TITLE
Current API is useless as posix_fadvise(3) works on open file descriptors

### ISSUE THREAD

**Issue by piotr1212** [lamby/python-fadvise#1]
python-fadvise module comes with pyadvise. I'm a bit confused of pyadvise's purpose. It opens a file, sets a posxi_fadvise and then closes the file again. From what I can tell from `man 3p posix_fadvise` the advise is only effective on open file descriptors and gets lost when the file is closed. Am I missing something or does pyadvise effectively do nothing?

**Comment by lamby** [comment]
Wow, how on earth did I not notice this. You are absolutely right. So, I guess it's still somewhat useful in that you can import from the private `_fadvise` module and manually call it on a file descriptor but yeah.

I think some kind of context manager would be an idea? How would you like to use it?

**Comment by piotr1212** [comment]
I am packaging python-fadvise for Fedora because one of the packages I maintain is using it like this:
https://github.com/graphite-project/whisper/blob/master/whisper.py#L56
https://github.com/graphite-project/whisper/blob/master/whisper.py#L413

This looks correct to me and seems to work.

When going through the rest of the files I got confused by the pyadvise script which is included.

**Comment by lamby** [comment]
ACK. I'll drop the script for now.

**Comment by lamby** [comment]
Updated the API just now

**Comment by lamby** [comment]
See also e76e4b0df57aa971374b4aea0078882348e5cae3

**Comment by zoharby** [comment]
FYI, the original script is still meaningful in some scenarios, as it will cause the OS to drop all currently cached blocks of this file. New data written to the file after this moment will still be cached.

This can be useful for example after log rotate / backup operations, telling the OS to drop the written files from the cache to free up memory for other files to be cached.

**Comment by lamby** [comment]
> in some scenarios

For which advice types were you thinking of, @zoharby?

**Comment by zoharby** [comment]
POSIX_FADV_DONTNEED will cause the OS to immediately drop all cached blocks of a file.
This can be done periodically (say every 60 seconds with a cron job) on files which are mainly "write only" (textual logs, DB transaction and replication logs, etc.), and can improve overall system performance.

I used this simple code:
http://insights.oetiker.ch/linux/fadvise.html
For this task, and it seems to be working as expected.

Indeed, newly written data to those files will still be cached, hence the need for a periodic job.

**Comment by piotr1212** [comment]
The files still get read into the cache, which potentially evicts old blocks. Dropping the cached blocks after they are there makes sense if you want the kernel prevent dropping older files which you know you will need. But it still feels a bit backwards to me..
I'm wondering if this cannot be implemented as a wrapper, for example the way nosync does this. 
https://github.com/kjn/nosync
Then you could prevent loading of the files at all.

**Comment by zoharby** [comment]
Indeed what I suggested is far from ideal, but given my scenario - a write intensive DB process, this is the best I can do. I know some files are rarely needed after being written (e.g. transaction logs which will be used only in case of a failure), so the best I can do is to tell the OS to drop these blocks from the cache as quickly as possible.
A wrapper that would do this only for specific files the DB process creates / modifies sounds quite complicated and risky...

**Comment by piotr1212** [comment]
In case of a DB I suggest you tune it the traditional way by grouping different types of files on separate partitions and or block devices. You can then set all sorts of settings on the partition or block device, for example blockdev --setra 0 to disable readahead caching.

**Comment by zoharby** [comment]
Makes sense, but many DBs don't have this kind of flexibility in terms of where to place different types of files (just 1 base folder under which all files are created). One can use soft links to "trick" the DB, but it's not something I would feel comfortable experimenting with.

**Comment by piotr1212** [comment]
Which DBMS are you referring to?

**Comment by zoharby** [comment]
We are using TokuMX, a variant of MongoDB.
It uses a single folder for all its data files. You can configure its transaction logs to a different folder, but not the replication oplog. 

But we're way out of scope from the original discussion...
